exp_name: 'example'

### Data path
train_data_path: '/home/semanos/VALIDATION/data/train/'                    # Training data
train_label_path: '/home/semanos/VALIDATION/data/features_trainset.csv' # Training label
valid_data_path: '/home/semanos/VALIDATION/data/test/'                    # Validation Data
valid_label_path: '/home/semanos/VALIDATION/data/features_testset2m.csv' # Validation Label

### output path
log_dir: '/home/semanos/VALIDATION//log/'
pred_dir: '/home/semanos/VALIDATION/pred/'
checkpoint_dir: '/home/semanos/VALIDATION/checkpoint/'

### Parameter
use_gpu: False             #
use_cpu: 2                # Number of cores to use for data loader
display_step: 2           # Std output update rate during training
test_step: 10             # Test per n step
learning_rate: 0.01     #
max_step: 100            # Number of steps to train
batch_size: 20            #
first_n_byte: 2000000     # First N bytes of a PE file as the input of MalConv (defualt: 2 million)
window_size: 500          # Kernel size & stride for Malconv (defualt : 500)
sample_cnt: 1             # Number of data sampled for trianing (defualt 1 = all)
